dark-matter-enterprises-description = A corporate conglomerate of mercenaries, scientists, physicians, engineers, merchants, contractors, and clowns all of which vary in qualifications, if any. Founded by unhinged ex-Nanotrasen Contractors, DME operates with one goal in mind: Profit. All members of the DME operate towards maximizing profit margins, for themselves alongside subsidiaries under the organization. DME functions under one core tenant called the Golden Rule which states “No infighting between enterprise members as this negatively affects profit margins.”

aetherion-dynamics-description = Representing the forefront of technological innovation, Aetherion Dynamics is renowned for their invention of the Compressed Gas Launch and Projectile (CGLP) system used in the ADEX-9 Dymere turbolaser battery, and additional innovative weapons with little to no consistent philosophy. Their close relations with the TSF grants them further autonomy than they might otherwise be granted. They have a reputation as high quality manufacturers and designers, more interested in building an effective product than on making a profit.

southern-peak-mercenaries-description = “A good rogue is a dead rogue.” says the slogan of this vicious mercenary company. The Southern Peaks were formed along the TSF-Rogue space border out retaliation against encroaching pirates and insurgents in combination with a sheer distrust of the TSFMC. Without the need of any other organization, TSP aims to fight back the Rogue Sector on its own.

zealots-of-balaam-description = The Zealots and pilgrims of Balaam are luddites with a extreme aversion to the use of Hi-tech. They are overtly isolationist, preferring to raid convoys that move too far into space. As a follower of the blessed god, work underneath a senior zealot to help them levy their tithes. Never listen to the blasphemy of the other companies. Kill those who profane Balaam's eye with the use of shield tech and FTL, heavy industry is not safe either.

viper-group-description = Formerly a privateering company domineered by military discipline with the sole mission of intercepting, disrupting and confiscating through TSF shipping routes along the fringes of USSP-TSF space in Sector 2. The Viper Group (VG) abruptly switched allegiances after a substantial number of tragic events in series. The TSF had offered the former-USSP backed organization substantial payment for subterfuge operations against the USSP, only to reveal them to the USSP soon after. Driven away by false bribes and murderous betrayal, TVG leadership was left to fester; often violently switching hands until “greed is good” eventually became the unspoken oath of membership. equitable relations with the Rogue Sector quickly expedited their arrival to rogue space. If you yearn for danger and wealth, join The Viper Group!

winter-solstice-description = All three branches of the Trans-Solar Marines Federation fall under the direction of the Federation's unified high command, known as Winter Solstice.

drake-industries-description = Smart & fast wins the race. What started of as a small transport company quickly became the lead in bulk transport & refining within the boundaries of the Collosus sector. Owning a monopoly in these domains allowed this corporation to grow exponentially amidst the high tensions in the sector and trade with all major groups without bias. The exclusive, hyper optimised ship-set it brought upon the market as part of it's expansion is highly prised for freelancers & corporation traders alike, despite the lack of comfort. Officially, it discourages any kind of hostilities performed by the members of the company. It promises easy profits to all capable pilots, traders & private securities who wish to apply. Don't act surprised when the working conditions are composed of throat-cutting deadlines, no bathroom breaks & sleeping on a dirty bedroll, though.

harmony-medical-enterprises-description = Harmony Medical Enterprises is a corporation based solely within medical practices and supplies, when you get hit in the battlefield? HME is the one that's provided your higher-ups with a discount deal on combat pens and various meds that keep you in the fight for longer. Harmony Medical Enterprises are the primary manufacturers that push things like medkits, combat pens, medipen cases, medical equipment, all of the lifesaving technology into the sector. While they have no dominion over cloning? They have the next best thing, medicine for the living.

steel-hammer-description = Massive industrial conglomerate, and Core Company. Specializes in the designing, construction, and outfitting of starship hulls employed by civilians, PMCs, or the highest bidder, utilizing grassroots startups, established industrial trade allies, and outsourced independent systems engineers. Key supplier of hulls and outfitted ships to the Colossus sector, making it one of the swords of the brewing conflict between the major factions vying for dominance. After the historical collapse of the Nanotrasen megacorporation and the Syndicate Allies, surviving profit-motivated hull manufacturing subsidiaries from both sides realized the best course of action was to separate as best they could from the destroyed powers and start anew. SHM accepts blueprints from all sorts of independent (or not) designers for all kinds of reasons, from improving the roster of universally available hulls on the intergalactic market, to… extremely valuable factional contracts. **Members of Steel Hammer Manufacturing are usually ship makers, breakers, designers, or maintainers.**
