using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockObject : PanelContainer
{
    public BoxContainer ContentsContainer => Contents;

    public DockObject()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PanelOverride = new StyleBoxFlat(new Color(30, 30, 34));
    }

    public void AddDock(DockingPortState state, ShuttleDockControl dockControl)
    {
        var dockLabel = new Label()
        {
            Text = "external airlock",
            HorizontalAlignment = HAlignment.Center,
        };
        
        var viewButton = new Button()
        {
            Text = Loc.GetString("View"),
        };

        viewButton.OnPressed += args =>
        {
            dockControl.SetViewedDock(state);
        };

        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Children =
            {
                dockLabel,
                viewButton
            }
        };

        DockContainer.AddChild(container);
    }

    public void SetName(string value)
    {
        DockedLabel.Text = value;
    }
}
